name: msds-ml3-rl
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.5
  - numpy=1.22
  - pandas=1.4
  - python=3.10
  - ipykernel=5.5.5
  - scikit-learn=0.24.2
  - seaborn=0.11.2
  - swig=4.0.2
  - torch=1.12
  - pip:
    - gym[Box_2D]==0.26.2
    - tensorflow==2.9
    - box2d==2.3.5
