name: msds-ml3-rl
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.5
  - numpy=1.22
  - pandas=1.4
  - python=3.10
  - ipykernel
  - seaborn=0.11.2
  - swig=4.0.2
  - pip:
    - gym[box2d]==0.26.2
    - torch==2.0.1