name: msds-ml3-rl
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.3.4
  - numpy=1.19.5
  - pandas=1.1.5
  - python=3.6.12
  - ipykernel=5.5.5
  - scikit-learn=0.24.2
  - seaborn=0.11.2
  - pip=21.3.1
  - scipy=1.5.3
  - notebook=6.3.0
  - swig=4.0.2
  - pip:
    - pyglet==1.5.21
    - gym[Box_2D]==0.21.0
    - tensorflow==2.6.2
    - box2d==2.3.10